eureka:
 client:
  register-with-eureka : true
  fetch-registry : true
  service-url:
   defaultZone: http://localhost:8091/eureka/
 instance:
  hostname: localhost



microservice:
 tez-shoppingmall:
  endpoints:
   endpoint:
    uri: http://TEZ-SHOPPINGMALL-PRODUCTS/products/GetChance

microservice:
 tez-orderservice:
   endpoints:
    endpoint:
     uri: http://localhost:8084/customerLogin/demo
   
